using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Data.Entity;
using LightERP.BaseModels;

namespace LightERP
{
    public partial class Form1 : DevExpress.XtraEditors.XtraForm
    {
        LightERP.ERD.BaseDB dbContext;
        public Form1()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            dbContext = new LightERP.ERD.BaseDB();
            //// Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            //dbContext.SEC_USERS.LoadAsync().ContinueWith(loadTask =>
            //{
            //    // Bind data to control when loading complete
            //    gridControl1.DataSource = dbContext.AccountBase.Local.ToBindingList();
            //            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            
            // Call the Load method to get the data for the given DbSet from the database.
          
        }

        private void Form1_Load(object sender, EventArgs e)
        {


            accountBaseBindingSource.DataSource = dbContext.LINE_BASE.ToList();
            
        }

        private void saveSB_Click(object sender, EventArgs e)
        {
            this.dbContext.SaveChanges();
        }
    }
}
